### ISSUE TITLE
Can't use general_autofill

### ISSUE THREAD

**Issue by 25Das** [ferreira-tb/tauri-plugin-prevent-default#13]
error[E0599]: no method named `general_autofill` found for struct `tauri_plugin_prevent_default::Builder` in the current scope
  --> src\lib.rs:85:18
   |
84 | /             tauri_plugin_prevent_default::Builder::new()
85 | |                 .general_autofill(false)
   | |                 -^^^^^^^^^^^^^^^^ method not found in `Builder<_>`
   | |_________________|
   | 

For more information about this error, try `rustc --explain E0599`.

Cargo.toml
[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-prevent-default = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

**Comment by ferreira-tb** [comment]
Hi. You need the `unstable-native-windows` feature:

```
tauri-plugin-prevent-default = { version = "0.7", features = ["unstable-native-windows"] }
```

I'll update the readme with this info.

**Comment by ferreira-tb** [comment]
I've updated the [README](https://github.com/ferreira-tb/tauri-plugin-prevent-default?tab=readme-ov-file#windows) with more information about this.

**Comment by 25Das** [comment]
> Hi. You need the `unstable-native-windows` feature:
> 
> ```
> tauri-plugin-prevent-default = { version = "0.7", features = ["unstable-native-windows"] }
> ```
> 
> I'll update the readme with this info.

Working flawlessly
