### ISSUE TITLE
Downgrade Minimum Supported Rust Version to 1.77.2 for Compatibility with Windows 7

### ISSUE THREAD

**Issue by zsman0520** [ferreira-tb/tauri-plugin-prevent-default#15]
Currently, the minimum supported Rust version for Tauri 2 is 1.77.2, which works on Windows 7. However, when using Rust version 1.78, the application crashes upon launch. Could you please consider downgrading the minimum Rust version to 1.77.2 to maintain compatibility with Windows 7?

Thank you for your attention to this matter.

**Comment by ferreira-tb** [comment]
That’s definitely something we can (and should) do. I’ll release a patch to address this.

**Comment by ferreira-tb** [comment]
Related: https://github.com/tauri-apps/tauri/pull/11205
