### ISSUE TITLE
MetaKey Modifier for macOS

### ISSUE THREAD

**Issue by AJNandi** [ferreira-tb/tauri-plugin-prevent-default#7]
Hi thanks for this plugin, seems to work great so far! 

I know macOS isn't fully tested but is it possible to add support for metaKey as a ModifierKey? Most of the macOS shortcuts we want to prevent default are MetaKey + [key].

**Comment by ferreira-tb** [comment]
Hi. That could be done. I'll release an update by tomorrow.

**Comment by AJNandi** [comment]
Amazing thank you!
